# Generated by Django 6.0.8 on 2026-09-09 01:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Customer code')),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='Customer name')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^[0-9+ -]{7,20}$')], verbose_name='Phone')),
                ('village', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Village')),
                ('customer_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('TEMPORARY', 'Temporary')], default='PERMANENT', max_length=20, verbose_name='Customer type')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Opening udhaar balance')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'phone', 'village'], name='customers_c_name_6bc4b3_idx')],
            },
        ),
    ]
