# Generated by Django 6.0.8 on 2026-09-09 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('action', models.CharField(max_length=80, verbose_name='Action')),
                ('module', models.CharField(max_length=80, verbose_name='Module')),
                ('object_reference', models.CharField(blank=True, max_length=160, verbose_name='Object reference')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chakki_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit event',
                'verbose_name_plural': 'Audit events',
                'ordering': ['-created_at'],
            },
        ),
    ]
