# Generated by Django 6.0.8 on 2026-09-09 01:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChakkiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('brand_name', models.CharField(default='Chakki ERP', max_length=120, verbose_name='Chakki brand name')),
                ('owner_name', models.CharField(blank=True, max_length=120, verbose_name='Owner name')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('village', models.CharField(blank=True, max_length=120, verbose_name='Village / locality')),
                ('currency_code', models.CharField(default='INR', max_length=8, verbose_name='Currency code')),
                ('currency_symbol', models.CharField(default='₹', max_length=8, verbose_name='Currency symbol')),
                ('default_language', models.CharField(choices=[('en', 'English'), ('hi', 'हिन्दी')], default='en', max_length=5, verbose_name='Default language')),
                ('default_grinding_rate', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=8, verbose_name='Default grinding rate per kg')),
                ('buyback_rates', models.JSONField(blank=True, default=dict, verbose_name='Default buyback rates')),
                ('invoice_footer', models.CharField(blank=True, max_length=255, verbose_name='Invoice footer')),
            ],
            options={
                'verbose_name': 'Chakki settings',
                'verbose_name_plural': 'Chakki settings',
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Configuration name')),
                ('provider', models.CharField(choices=[('UPI', 'UPI / Bank Dynamic QR'), ('RAZORPAY', 'Razorpay'), ('BHARATPE', 'BharatPe'), ('CUSTOM', 'Custom Bank / UPI Provider')], default='UPI', max_length=20, verbose_name='Provider')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default gateway')),
                ('upi_vpa', models.CharField(blank=True, max_length=120, verbose_name='UPI VPA / merchant address')),
                ('merchant_name', models.CharField(blank=True, max_length=120, verbose_name='Merchant display name')),
                ('merchant_id', models.CharField(blank=True, max_length=120, verbose_name='Merchant ID')),
                ('key_id', models.CharField(blank=True, max_length=180, verbose_name='API key / key ID')),
                ('key_secret_encrypted', models.TextField(blank=True, editable=False)),
                ('webhook_secret_encrypted', models.TextField(blank=True, editable=False)),
                ('webhook_signature_header', models.CharField(default='X-Chakki-Signature', help_text='Examples: X-Chakki-Signature or X-Razorpay-Signature.', max_length=80, verbose_name='Webhook signature header')),
                ('signature_algorithm', models.CharField(choices=[('HMAC_SHA256', 'HMAC SHA-256 (hex digest)')], default='HMAC_SHA256', max_length=24, verbose_name='Webhook signature algorithm')),
                ('currency_code', models.CharField(default='INR', max_length=8, verbose_name='Currency')),
                ('provider_base_url', models.URLField(blank=True, verbose_name='Provider API base URL')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Provider metadata')),
            ],
            options={
                'verbose_name': 'Payment / UPI gateway',
                'verbose_name_plural': 'Payment / UPI gateways',
                'ordering': ['-is_default', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='single_default_payment_gateway')],
            },
        ),
    ]
