# Generated by Django 6.0.8 on 2026-09-09 01:51

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Account code')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Account name')),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=12, verbose_name='Account type')),
                ('system_key', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='System key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Ledger account',
                'verbose_name_plural': 'Ledger accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='OldUdhaar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Original opening amount')),
                ('settled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Settled amount')),
                ('opening_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Opening date')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
            ],
            options={
                'ordering': ['-opening_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('entry_number', models.CharField(max_length=30, unique=True, verbose_name='Journal number')),
                ('entry_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Entry date')),
                ('narration', models.CharField(max_length=255, verbose_name='Narration')),
                ('source_type', models.CharField(blank=True, max_length=50, verbose_name='Source type')),
                ('source_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Source ID')),
                ('posted', models.BooleanField(default=True, verbose_name='Posted')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chakki_journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Receipt amount')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI / QR'), ('BANK', 'Bank transfer'), ('ADJUSTMENT', 'Adjustment')], default='CASH', max_length=20, verbose_name='Payment method')),
                ('reference', models.CharField(blank=True, max_length=80, verbose_name='Reference')),
                ('receipt_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Receipt date')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='customers.customer', verbose_name='Customer')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_receipt', to='accounting.journalentry')),
            ],
            options={
                'ordering': ['-receipt_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Debit')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Credit')),
                ('transactional_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='Transactional balance')),
                ('line_memo', models.CharField(blank=True, max_length=255, verbose_name='Line memo')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='accounting.account', verbose_name='Ledger account')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='customers.customer', verbose_name='Customer')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='accounting.journalentry', verbose_name='Journal entry')),
            ],
            options={
                'ordering': ['journal_entry__entry_date', 'id'],
            },
        ),
    ]
