# Generated by Django 6.0.8 on 2026-09-09 01:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('sku', models.CharField(max_length=30, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=120, verbose_name='Item name')),
                ('category', models.CharField(choices=[('RAW_GRAIN', 'Raw grain'), ('FINISHED', 'Ground atta / finished flour'), ('OIL', 'Cold-press oil'), ('BYPRODUCT', 'Khal / by-product'), ('PACKAGING', 'Gunny bag / packaging'), ('SPARE', 'Machine spare'), ('OTHER', 'Other')], max_length=20, verbose_name='Category')),
                ('unit', models.CharField(choices=[('KG', 'Kg'), ('LITRE', 'Litre'), ('PIECE', 'Piece'), ('BAG', 'Bag')], default='KG', max_length=12, verbose_name='Unit')),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Quantity on hand')),
                ('reorder_level', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Reorder level')),
                ('standard_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Standard cost per unit')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Selling price per unit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Supplier code')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Supplier name')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('gstin', models.CharField(blank=True, max_length=20, verbose_name='GSTIN')),
                ('opening_payable', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Opening payable')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('movement_type', models.CharField(choices=[('OPENING', 'Opening stock'), ('PURCHASE', 'Purchase receipt'), ('SALE', 'Retail sale'), ('PRODUCTION_IN', 'Production output'), ('PRODUCTION_OUT', 'Production input'), ('BUYBACK', 'Customer buyback'), ('WASTAGE', 'Wastage'), ('ADJUSTMENT', 'Stock adjustment')], max_length=20, verbose_name='Movement type')),
                ('quantity_delta', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantity change')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Reference')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Occurred at')),
                ('balance_after', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Balance after movement')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventoryitem', verbose_name='Inventory item')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('purchase_number', models.CharField(blank=True, max_length=24, unique=True, verbose_name='Purchase number')),
                ('invoice_reference', models.CharField(blank=True, max_length=80, verbose_name='Supplier invoice reference')),
                ('purchase_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Purchase date')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total purchase amount')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Amount paid')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12, verbose_name='Status')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase', to='accounting.journalentry')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='inventory.supplier', verbose_name='Supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='inventory.inventoryitem')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.purchase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('sale_number', models.CharField(blank=True, max_length=24, unique=True, verbose_name='Sale number')),
                ('sale_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sale date')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI / QR'), ('CREDIT', 'Credit / Udhaar')], default='CASH', max_length=12, verbose_name='Payment method')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total sale amount')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retail_sales', to='customers.customer', verbose_name='Customer')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retail_sale', to='accounting.journalentry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='inventory.inventoryitem')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
