# Generated by Django 6.0.8 on 2026-09-09 01:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('employee_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Employee code')),
                ('name', models.CharField(max_length=120, verbose_name='Employee name')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('role_title', models.CharField(blank=True, max_length=80, verbose_name='Role / job title')),
                ('employment_type', models.CharField(choices=[('MONTHLY', 'Monthly salary'), ('DAILY', 'Daily wage'), ('CONTRACT', 'Contract')], default='DAILY', max_length=12, verbose_name='Employment type')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On leave'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=12, verbose_name='Employment status')),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Monthly salary')),
                ('daily_wage', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Daily wage')),
                ('joined_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='Joined on')),
                ('contract_notes', models.TextField(blank=True, verbose_name='Contract parameters')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('maintenance_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Maintenance date')),
                ('machine_name', models.CharField(max_length=120, verbose_name='Machine')),
                ('service_type', models.CharField(choices=[('BELT', 'Belt replacement'), ('BEARING', 'Bearing lubrication / replacement'), ('STONE', 'Stone channelling / Takai'), ('MOTOR', 'Motor service'), ('CLEANING', 'Cleaning'), ('OTHER', 'Other')], max_length=20, verbose_name='Service type')),
                ('meter_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Machine hours')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Next due date')),
                ('next_due_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Next due machine hours')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Maintenance cost')),
                ('performed_by', models.CharField(blank=True, max_length=120, verbose_name='Performed by')),
                ('details', models.TextField(blank=True, verbose_name='Details')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_log', to='accounting.journalentry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('period_start', models.DateField(verbose_name='Period start')),
                ('period_end', models.DateField(verbose_name='Period end')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('PAID', 'Paid')], default='DRAFT', max_length=12, verbose_name='Status')),
                ('total_net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total net pay')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_run', to='accounting.journalentry')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('workdays', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Active workdays')),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gross pay')),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Deductions')),
                ('advances', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Advances')),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Net pay')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_lines', to='workforce.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='workforce.payrollrun')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('attendance_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Date')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='Check in')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Check out')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half day'), ('LEAVE', 'Leave')], default='PRESENT', max_length=12, verbose_name='Attendance status')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='workforce.employee', verbose_name='Employee')),
            ],
            options={
                'ordering': ['-attendance_date', 'employee__name'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'attendance_date'), name='unique_employee_attendance_day')],
            },
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('period_start', 'period_end'), name='unique_payroll_period'),
        ),
        migrations.AddConstraint(
            model_name='payrollline',
            constraint=models.UniqueConstraint(fields=('payroll_run', 'employee'), name='unique_payroll_employee'),
        ),
    ]
