# Generated by Django 6.0.8 on 2026-09-09 01:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('configuration', '0001_initial'),
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('production_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Production date')),
                ('product_name', models.CharField(max_length=120, verbose_name='Product')),
                ('input_weight_kg', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Input raw weight (kg)')),
                ('output_weight_kg', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Finished output (kg)')),
                ('byproduct_weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='By-product output (kg)')),
                ('process_loss_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Process loss (kg)')),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WastageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('wastage_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Wastage date')),
                ('process', models.CharField(max_length=120, verbose_name='Process')),
                ('input_weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Reference input (kg)')),
                ('milling_loss_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Milling loss (kg)')),
                ('dust_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Dust (kg)')),
                ('other_waste_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Other waste (kg)')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Reason')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuybackTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('reference', models.CharField(blank=True, max_length=24, unique=True, verbose_name='Buyback reference')),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Processing / extraction fee')),
                ('buyback_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Products bought back value')),
                ('net_customer_payable', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Net amount payable to customer')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buybacks', to='customers.customer', verbose_name='Customer')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buyback', to='accounting.journalentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuybackLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('product_type', models.CharField(choices=[('KHAL', 'Khal'), ('ATTA', 'Atta'), ('OIL', 'Oil'), ('BRAN', 'Bran / Chokar'), ('OTHER', 'Other')], max_length=20, verbose_name='Product')),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantity (kg)')),
                ('system_rate_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='System buyback rate')),
                ('applied_rate_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Applied buyback rate')),
                ('override_reason', models.CharField(blank=True, max_length=255, verbose_name='Override reason')),
                ('line_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Line value')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyback_lines', to='inventory.inventoryitem', verbose_name='Inventory item')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='operations.buybacktransaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrindingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('order_number', models.CharField(blank=True, max_length=24, unique=True, verbose_name='Order number')),
                ('status', models.CharField(choices=[('INTAKE', 'Intake'), ('GRINDING', 'Grinding Stage'), ('READY', 'Ready'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='INTAKE', max_length=20, verbose_name='Order status')),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially paid'), ('PAID', 'Paid')], db_index=True, default='UNPAID', max_length=20, verbose_name='Payment status')),
                ('promised_at', models.DateTimeField(blank=True, null=True, verbose_name='Promised at')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='Ready at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered at')),
                ('notes', models.TextField(blank=True, verbose_name='Order notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chakki_orders_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grinding_orders', to='customers.customer', verbose_name='Customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='buybacktransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buybacks', to='operations.grindingorder', verbose_name='Related order'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('invoice_number', models.CharField(blank=True, max_length=24, unique=True, verbose_name='Invoice number')),
                ('total_grinding_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total grinding fee')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Paid amount')),
                ('forgiven_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Forgiven amount')),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Outstanding udhaar')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIAL', 'Partially paid'), ('PAID', 'Paid'), ('VOID', 'Void')], default='OPEN', max_length=12, verbose_name='Invoice status')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grinding_invoice', to='accounting.journalentry')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='operations.grindingorder', verbose_name='Grinding order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('QR', 'Dynamic QR / UPI'), ('CREDIT', 'Credit / Udhaar'), ('BANK', 'Bank')], default='QR', max_length=12, verbose_name='Payment method')),
                ('payment_reference', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Payment reference')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Payment amount')),
                ('settlement_status', models.CharField(choices=[('PENDING', 'Pending'), ('SETTLED', 'Settled'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=12, verbose_name='Settlement status')),
                ('provider', models.CharField(blank=True, max_length=80, verbose_name='Payment provider snapshot')),
                ('provider_payload', models.JSONField(blank=True, default=dict, verbose_name='Provider payload')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='Settled at')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='operations.invoice', verbose_name='Invoice')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_payment', to='accounting.journalentry')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='operations.grindingorder', verbose_name='Grinding order')),
                ('payment_gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_payments', to='configuration.paymentgatewayconfig', verbose_name='Payment / UPI gateway')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('from_status', models.CharField(blank=True, choices=[('INTAKE', 'Intake'), ('GRINDING', 'Grinding Stage'), ('READY', 'Ready'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('to_status', models.CharField(choices=[('INTAKE', 'Intake'), ('GRINDING', 'Grinding Stage'), ('READY', 'Ready'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='operations.grindingorder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('grain_type', models.CharField(choices=[('WHEAT', 'Wheat'), ('CHANA', 'Chana'), ('MULTIGRAIN', 'Multigrain'), ('MUSTARD', 'Mustard'), ('OTHER', 'Other')], max_length=20, verbose_name='Grain')),
                ('flour_type', models.CharField(choices=[('ATTA', 'Atta'), ('BESAN', 'Besan'), ('MULTIGRAIN', 'Multigrain'), ('OIL', 'Oil extraction'), ('OTHER', 'Other')], max_length=20, verbose_name='Output / service')),
                ('service_name', models.CharField(blank=True, max_length=120, verbose_name='Custom service name')),
                ('with_jalan', models.BooleanField(default=False, verbose_name='With Jalan')),
                ('system_rate_per_kg', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='System rate per kg')),
                ('allow_override', models.BooleanField(default=True, verbose_name='Allow operator override')),
                ('minimum_rate_per_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Minimum allowed rate')),
                ('maximum_rate_per_kg', models.DecimalField(decimal_places=2, default=Decimal('999.00'), max_digits=8, verbose_name='Maximum allowed rate')),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate, verbose_name='Effective from')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'ordering': ['grain_type', 'flour_type', 'with_jalan'],
                'constraints': [models.UniqueConstraint(fields=('grain_type', 'flour_type', 'with_jalan', 'effective_from'), name='unique_rate_effective_date')],
            },
        ),
        migrations.CreateModel(
            name='GrindingOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('grain_type', models.CharField(choices=[('WHEAT', 'Wheat'), ('CHANA', 'Chana'), ('MULTIGRAIN', 'Multigrain'), ('MUSTARD', 'Mustard'), ('OTHER', 'Other')], max_length=20, verbose_name='Grain')),
                ('flour_type', models.CharField(choices=[('ATTA', 'Atta'), ('BESAN', 'Besan'), ('MULTIGRAIN', 'Multigrain'), ('OIL', 'Oil extraction'), ('OTHER', 'Other')], max_length=20, verbose_name='Output / service')),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Weight (kg)')),
                ('with_jalan', models.BooleanField(default=False, verbose_name='With Jalan')),
                ('system_rate_per_kg', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='System rate per kg')),
                ('applied_rate_per_kg', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Applied rate per kg')),
                ('rate_override_reason', models.CharField(blank=True, max_length=255, verbose_name='Rate override reason')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Line total')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='operations.grindingorder', verbose_name='Grinding order')),
                ('rate_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='operations.ratecard', verbose_name='Rate card')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UtilityLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('period', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Billing / usage date')),
                ('utility_type', models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('DIESEL', 'Diesel / Fuel'), ('WATER', 'Water'), ('OTHER', 'Other overhead')], max_length=20, verbose_name='Utility type')),
                ('units', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Units / quantity')),
                ('unit_label', models.CharField(default='unit', max_length=20, verbose_name='Unit label')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Cost')),
                ('reference', models.CharField(blank=True, max_length=80, verbose_name='Bill reference')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utility_cost', to='accounting.journalentry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='grindingorder',
            index=models.Index(fields=['status', 'created_at'], name='operations__status_d91198_idx'),
        ),
        migrations.AddIndex(
            model_name='grindingorder',
            index=models.Index(fields=['customer', 'created_at'], name='operations__custome_5e2c9d_idx'),
        ),
    ]
